### ISSUE TITLE
`experimentalNeo4jQuery`: return `cid` with payload

### ISSUE THREAD

**Issue by MichaelHirn** [rlay-project/rlay-client#35]
At the moment when you are calling `experimentalNeo4jQuery` you are getting the full entity body of the `CID`s that are returned by the query:

```js
web3.rlay.experimentalNeo4jQuery('MATCH ... RETURN n.cid');
```

returns something like

```js
[ { type: 'ClassAssertion', subject: '0x00...', class: '0x01...' }, ... ]
```

However, these entity bodies are not including the `cid` of the entity, which omits important information, when processing the results of `experimentalNeo4jQuery`. For example:

The following is a query, that fetches all assertions for an individual and returns their cid as well as the cid of the individual that an `ObjectPropertyAssertion` is pointing to, which makes it an extremly powerful and fast query.

```cypher
MATCH (n:RlayEntity {cid: "..."})-[r]-(m)
OPTIONAL MATCH
 (m)-[:target]-(o)
WHERE type(r) = "subject"
WITH m.cid + COLLECT(o.cid) AS cids
UNWIND cids AS cid
RETURN DISTINCT cid
```

calling `experimentalNeo4jQuery` returns all the correct entity bodies, but because their `cid`s are omitted, it is not possible to assign the `Individual`s to the correct `ObjectPropertyAssertion`.

**Comment by hobofan** [comment]
Fixed with 3902d24b3b6a9ea6c47042d108e0d259700a744b
